server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:study_platform.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create-drop   # было: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: never             # отключаем init.sql, чтобы он не мешался
websocket:
  channels:
    test: true

logging:
  level:
    org.hibernate.SQL: DEBUG
security:
  jwt:
    secret: "ChangeThisSecretKeyToAStrongRandomValue1234567890"
    expiration-ms: 3600000
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
